- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
